### ISSUE TITLE
Game crashes upon loading world

### ISSUE THREAD

**Issue by md678685** [zhuowei/Boardwalk#259]
Minecraft version: 1.9
Android version: 5.0.2
Model: Xiaomi Redmi Note 2 (running MIUI 7 beta 6.2.25 by xiaomi.eu)

When attempting to connect to a server or load a world, the game crashes with an error. 

Crash report:

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 08/03/2016 13:10
Description: Unexpected error

java.lang.NullPointerException: Attempt to read from field 'double rr.p' on a null object reference
	at aht.a(SourceFile:1174)
	at bng.h(SourceFile:1591)
	at bng.a(SourceFile:1180)
	at bng.b(SourceFile:1165)
	at bng.a(SourceFile:1012)
	at bcf.av(SourceFile:985)
	at bcf.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at net.zhuoweizhang.boardwalk.MainActivity.runCraft2(MainActivity.java:633)
	at net.zhuoweizhang.boardwalk.MainActivity$3.onSurfaceCreated(MainActivity.java:213)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at aht.a(SourceFile:1174)
	at bng.h(SourceFile:1591)
	at bng.a(SourceFile:1180)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 8, 8
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9 game time, 9 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'java.lang.String bmt.E()' on a null object reference
	Server type: Integrated singleplayer server
Stacktrace:
	at aht.a(SourceFile:2833)
	at bku.a(SourceFile:365)
	at bcf.b(SourceFile:2515)
	at bcf.a(SourceFile:406)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at net.zhuoweizhang.boardwalk.MainActivity.runCraft2(MainActivity.java:633)
	at net.zhuoweizhang.boardwalk.MainActivity$3.onSurfaceCreated(MainActivity.java:213)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (aarch64) version 3.10.61+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (null), The Android Project
	Memory: 0 bytes (0 MB) / 137434544 bytes (131 MB) up to 268435456 bytes (256 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.9
	LWJGL: 2.9.1
	OpenGL: GLES_CM wrapper GL version 1.4 glshim wrapper, OpenPandora
	GL Caps: Using ARB_multitexture.
Using ARB_texture_env_combine.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is not supported, and EXT_framebuffer_object is not supported.
Shaders are not available because OpenGL 2.1 is not supported, ARB_shader_objects is not supported, ARB_vertex_shader is not supported, and ARB_fragment_shader is not supported.
VBOs are not available because 
	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'Boardwalk'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 5x

**Comment by md678685** [comment]
Sorry, this got formatted by GH, raw version [here](https://gist.github.com/md678685/641151152fcc8433ac5c).

**Comment by zhuowei** [comment]
Try beta: http://zhuoweizhang.net/Boardwalk/Boardwalk-release.apk

**Comment by md678685** [comment]
https://gist.github.com/md678685/c9ae677e003598961153

It still appears to crash with the same NPE.
