### ISSUE TITLE
I want to help!!!

### ISSUE THREAD

**Issue by Chanakan6771** [zhuowei/Boardwalk#293]
Description: Registering texture
java.lang.OutOfMemoryError: Java heap space
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:241)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:232)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:194)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:48)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45)
	at net.minecraft.client.gui.FontRenderer.bindTexture(FontRenderer.java:854)
	at net.minecraft.client.gui.FontRenderer.<init>(FontRenderer.java:57)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:488)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:241)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:232)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:194)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:48)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/font/ascii.png
	Texture object class: net.minecraft.client.renderer.texture.SimpleTexture
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45)
	at net.minecraft.client.gui.FontRenderer.bindTexture(FontRenderer.java:854)
	at net.minecraft.client.gui.FontRenderer.<init>(FontRenderer.java:57)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:488)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.7.0_79, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
	Memory: 4204480 bytes (4 MB) / 518979584 bytes (494 MB) up to 518979584 bytes (494 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 45 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCH	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCH	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCH	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCH	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (Malisis' Core.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles.jar) 
	UCH	surpriseeggs{1.0.6} [Surprise Eggs] (Adventure Backpack.jar) 
	UCH	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (Adventure Backpack.jar) 
	UCH	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI.jar) 
	UCH	armourersWorkshop{1.7.10-0.33.0.84} [Armourer's Workshop] (Armourer's Workshop.jar) 
	UCH	asielib{0.2.7} [asielib] (asielib.jar) 
	UCH	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft.jar) 
	UCH	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks.jar) 
	UCH	Railcraft{9.6.1.0} [Railcraft] (Railcraft.jar) 
	UCH	chisel{2.3.10.37} [Chisel 2] (Chisel 2.jar) 
	UCH	RDMenuServer{2.0.0.2} [RDMenuServer] (CustomMenu.jar) 
	UCH	customnpcs{1.7.10d} [CustomNpcs] (CustomNpcs.jar) 
	UCH	DamageIndicatorsMod{3.2.3} [Damage Indicators] (Damage Indicators.jar) 
	UCH	darkcore{0.3} [Dark Core] (Dark Core.jar) 
	UCH	props{2.0.2} [Decocraft] (Decocraft.jar) 
	UCH	EE3{0.3.507} [Equivalent Exchange 3] (Equivalent Exchange 3.jar) 
	UCH	iChunUtil{4.2.2} [iChunUtil] (iChunUtil.jar) 
	UCH	GraviGun{4.0.0-beta} [GraviGun] (GravityGun.jar) 
	UCH	Hats{4.0.1} [Hats] (Hats.jar) 
	UCH	HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar) 
	UCH	InventoryPets{1.1.2a} [Inventory Pets] (Inventory Pets.jar) 
	UCH	IronChest{6.0.60.741} [Iron Chest] (Iron Chest.jar) 
	UCH	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (Malisis' Doors.jar) 
	UCH	MobProperties{0.4.0} [Mob Properties] (Mob Properties.jar) 
	UCH	Morph{0.9.1} [Morph] (Morph.jar) 
	UCH	MutantCreatures{1.4.8} [Mutant Creatures] (Mutant Creatures.jar) 
	UCH	MapWriter{2.1.2} [MapWriter] (Opis.jar) 
	UCH	Opis{1.2.5} [Opis] (Opis.jar) 
	UCH	origin{3.3.0} [Origin] (Origin.jar) 
	UCH	pandorasbox{2.0.1} [Pandora's Box] (Pandora's Box.jar) 
	UCH	PortalGun{4.0.0-beta-4} [PortalGun] (PortalGun-4.0.0-beta-4.jar) 
	UCH	SaintsCore{0.8} [Saintscore] (Saintscore.jar) 
	UCH	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (Soul Shards- The Old Ways.jar) 
	UCH	statues{2.1.3} [Statues] (Statues.jar) 
	UCH	TardisMod{0.99} [Tardis Mod] (Tardis Mod.jar) 
	UCH	secretroomsmod{4.7.1} [The SecretRoomsMod] (The SecretRoomsMod.jar) 
	UCH	TrailMix{4.0.0} [TrailMix] (TrailMix.jar) 
	UD	asielibcore{} [AsieLib CoreMod] (minecraft.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 2500'
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 2500 GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Tackle_ResourcePack, yandere skin]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[18:39:21] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Kan\AppData\Roaming\.minecraft\crash-reports\crash-2016-09-23_18.39.21-client.txt

**Comment by Fungie2134** [comment]
Your device do not have enough memory to launch with some many mods.
