### ISSUE TITLE
Nougat ZipException

### ISSUE THREAD

**Issue by HAlexTM** [zhuowei/Boardwalk#304]
S7 edge, Nougat 7.0
![Screenshot](http://i.imgur.com/8UbQjN2h.jpg(
As seen in #302

@zhuowei, I'd like to work with you on the project, is it possible?

**Comment by minealex2244** [comment]
I think that no. This is closed source. Same issue here but it is related to the new storage framework used in Android N. This app is not yet upgraded to that API.

**Comment by HAlexTM** [comment]
Well, I asked Zhuowei ahah

**Comment by minealex2244** [comment]
Can you tell me the coding languages you know? I'm planning to decompile the app and to see what I can do to test it (unfortunately it will be just for myself as it is illegal to redistribute this app but I'll see what I can do).

**Comment by HAlexTM** [comment]
I decompiled it an hour ago but I found some lib (.so file) which I only seen with the hex editor, it's 6KB and doesn't seem to be part of the execution

Anyway I know Java, PHP, HTML, JS, CSS, SQL and maybe something else (which I can't remember right now)

**Comment by minealex2244** [comment]
That's cool. :D I think there isn't anything important in the .so files but there is something in the Storage access classes. Google made some modifications to the Storage Access Framework which is just a pain for Devs. I will try to see if there is any workaround.

**Comment by HAlexTM** [comment]
Alright, I'll see too, let me setup the project

Il Ven 14 Apr 2017, 4:48 PM Pop Alexandru Radu <notifications@github.com>
ha scritto:

**Comment by minealex2244** [comment]
Here is the logcat I've taken:
---- 14 apr. 2017 18:28:31 ----

04-14 18:26:29.399  4112  4760 I System.out: Dex pack: /data/user/0/net.zhuoweizhang.boardwalk/app_working_dir/dex_pack/1.9.jar

04-14 18:26:29.406  4112  4760 I System.out: Dex pack: /data/user/0/net.zhuoweizhang.boardwalk/app_working_dir/dex_pack/1.9.jar

04-14 18:26:30.291  4112  4760 I System.out: Dex pack: /data/user/0/net.zhuoweizhang.boardwalk/app_working_dir/dex_pack/1.9.jar

04-14 18:26:30.297  4112  4760 I System.out: Renaming: /data/user/0/net.zhuoweizhang.boardwalk/app_working_dir/versions/1.9/1.9.jar to /data/user/0/net.zhuoweizhang.boardwalk/app_working_dir/tmp/1.9.jar1267705696.jar

04-14 18:27:16.349  4112  4760 W System.err: 	at net.zhuoweizhang.boardwalk.util.IoUtil.pipe(IoUtil.java:33)

04-14 18:27:16.349  4112  4760 W System.err: 	at net.zhuoweizhang.boardwalk.util.CleanZipUtil.shardZip(CleanZipUtil.java:124)

04-14 18:27:16.349  4112  4760 W System.err: 	at net.zhuoweizhang.boardwalk.downloader.MinecraftLaunch.createDexPack(MinecraftLaunch.java:64)

04-14 18:27:16.349  4112  4760 W System.err: 	at net.zhuoweizhang.boardwalk.LaunchMinecraftTask.downloadMinecraft(LaunchMinecraftTask.java:127)

04-14 18:27:16.349  4112  4760 W System.err: 	at net.zhuoweizhang.boardwalk.LaunchMinecraftTask.doInBackground(LaunchMinecraftTask.java:47)

04-14 18:27:16.349  4112  4760 W System.err: 	at net.zhuoweizhang.boardwalk.LaunchMinecraftTask.doInBackground(LaunchMinecraftTask.java:15)

---- 14 apr. 2017 18:28:31 ----

**Comment by HAlexTM** [comment]
ok thanks for the logcat let me see what's in the Java file

**Comment by HAlexTM** [comment]
And that's just one error, I don't really know what's happening
![screen](http://i.imgur.com/z0cJG6l.png)

**Comment by minealex2244** [comment]
Which tool did you used to decompile the apk file? A JadX based one? I ask this because I like the way the app was decompiled.

**Comment by HAlexTM** [comment]
@minealex2244
I used dex2jar for the jar and jd-gui for the .java files

**Comment by minealex2244** [comment]
I know a lot of tools​ to decompile apks but I see that your apk was decompiled very good. I don't mean the IDE but it is cool too. Now that I have some free time I'll try to decompile it to see what's inside.

**Comment by AbhiTheBoss** [comment]
Same as #299

**Comment by 2F4Uof2b2t** [comment]
How has the app decompiled for you guys? I've written in java for a long time and I've had the idea to decompile it and see if I can fix it (it should be simple), but I'm not sure if it'll even decompile correctly.

**Comment by 2F4Uof2b2t** [comment]
How has the app decompiled for you guys? I've written in java for a long time and I've had the idea to decompile it and see if I can fix it (it should be simple), but I'm not sure if it'll even decompile correctly.

**Comment by zhuowei** [comment]
@2F4Uof2b2t Decompilers won't give recompilable code. Disassemblers may work, but please don't.

**Comment by HAlexTM** [comment]
@zhuowei you should provide a way to fix these issues.
The app is unusable right now.

**Comment by zhuowei** [comment]
I know, and I have plans for a rewrite.

**Comment by HAlexTM** [comment]
@zhuowei ok, thank you.

**Comment by gingerbryn1** [comment]
@khanhduytran0 could you elaborate, any help would be great as I've been at this for over a year ;-;

**Comment by khanhduytran0** [comment]
3 builds! If it only a black screen tell me
https://drive.google.com/file/d/1LGLBKvN4V1nPyAkkQblbJ5z6zuvdHaqs/view?usp=drivesdk
I am adding Screenshot button but no output
Adding TAB (list players)

**Comment by zhuowei** [comment]
@khanhduytran0 This doesn't look like Boardwalk 1.9 - it's using the regular Android ART runtime, not Boardwalk 1.9's (failed) attempt to use a different runtime. Also, pretty sure distributing Minecraft JARs pre-dexed in the APK breaks the Minecraft license.

Why gl4es instead of glShim? Does it work better? I might switch to it for Boardwalk 2.

I haven't tried this: how well does it run on newer phones?

I should probably yell at you for using Boardwalk code without permission, (and I might need to ask you to take this down), but for now, good work.

**Comment by khanhduytran0** [comment]
@zhuowei
Everything is too hard because iam a noob.
Login account?login Mojang account won't working for now
although i have added gl4es with gl2.0 backend but seems like not working (also Require gl2.0 in minecraft And if missing glshim app crash)
Newer phone? Android 9.0?
Button Login with account, But currently NOT working due to tokens is wrong: can't load skin, can't login to some servers like Hypixel
Mods: The original was an idea, very ambiguous, i don't know: does it use AWT or only Forge Api?
License: oh sorry, i dev for experiment, so just for fun :<)

Detect error Can't convert by after jarjar rename, classes file is corrupt in android 6.0 or later (unless libraries) try by use other dexer tools: jar2dex or dex with AIDE dexed but when run i get can't find class 
 net.minecraft.client.main.Main !  So if you simulate java (jre) in android (only for run jarjar) likely working!
Or you need a time to refer jarjar source code.
Good luck!

**Comment by minealex2244** [comment]
It is working pretty well on newer devices. I have a Samsung Galaxy S9 and I'm getting 30+ fps. Sometimes I'm getting 60 fps with just view bobbing enabled and with chunks rendering set to 5. Water is causing lag because of the animation. Optifine would fix everything. Good work @khanhduytran0 👍🏻

**Comment by khanhduytran0** [comment]
@minealex2244 if add Optifine, need something to detect latest version of Optifine for different Minecraft version.
Is Optifine have a download api? If have, ...

**Comment by gingerbryn1** [comment]
@khanhduytran0  have you already taken down the repository ;-;

**Comment by minealex2244** [comment]
@khanhduytran0 I have used 1.7.10. I'm not sure about Optifine API. I'll search for it.

**Comment by Letfordlay** [comment]
@khanhduytran0 where is the download for your app? I would love to try it on my galaxy s9

**Comment by gingerbryn1** [comment]
@khanhduytran0 this is impressive

**Comment by Letfordlay** [comment]
@khanhduytran0 It runs very well on my galaxy s9, very impressive!

**Comment by sgdc3** [comment]
@khanhduytran0 could you publish the sources?

**Comment by khanhduytran0** [comment]
@sgdc3 use Apkeditorpro.apk to get sources (BUT it is not Apk decompiler, only decompile each file, not decompile ALL classes once)

**Comment by khanhduytran0** [comment]
@sgdc3 use Apkeditorpro.apk to get sources (BUT it is not Apk decompiler, only decompile each file, not decompile ALL classes once)
http://dl12.sopcast.mobi/download/s/20180328/qUoFsu2j7FfOvpEt-h934w/1539305980/APK_Editor_Pro_191apk.apk

**Comment by EmotionalLove** [comment]
@zhuowei I feel like if you made Boardwalk an open source project that it would be more successful if the community could contribute to the project with pull requests. For example @khanhduytran0 got it running on Android 7 and up _and_ it runs _very_ smooth (60fps on my GS9)

You should seriously considering publishing the sources under an open source license like the GPL3 and accepting pr's.

**Comment by zhuowei** [comment]
@EmotionalLove My plan is to replace Boardwalk's Java layer to support modloaders: I've started on that during March and laid some of the groundwork and will pick it up again during this month.

Once that's released, I'll see if I can make Boardwalk 1 open source.

**Comment by JulianARG** [comment]
OMG THIS IS AMAZING, I have been able to play in this application on my Xiaomi Mi A2 Lite that has a Snapdragon 625, a medium range that ran to 20 - 30 in a normal world OMFG !, I realized that water gives a lot of lag, true ? In a flat world the fps
up to 45, thank you very much, really.
Some questions:
Can I install optifine to improve performance?
Could I upload this to YouTube in order to make it known to more people? If the answer is no, there's no problem, I'll understand
the multiplayer is available? I wish it were out
hopefully continue with this project working in community
Greetings from Argentina, guys. I apologize for my bad English

**Comment by khanhduytran0** [comment]
#JulianARG
Maybe true, but the chunks update also give you lag.
Answer:
 .I don't know. But I will try to implement Optifine.
 .Yes, but you must leave the source!!!🤔 I see a youtuber review without leave the source 😥
 .Yes, you can play multiplayer (and cracked servers)
 .Continue but only 1.7.10 🤔 because other versions are too lag.

**Comment by JulianARG** [comment]
Hello, Thank you very much for answering, could you solve the chunks? or is it my mobile's fault?
I hope I can try optifine, and thank you very much for letting this go to YouTube, I will leave all the credits.
What a joy that servers can play in the 1.7!
Hopefully if at any time the project is updated I hope to be aware of them.

**Comment by khanhduytran0** [comment]
I think no, chunks load/save make game lag.
Thank you for sharing and trying.

**Comment by JulianARG** [comment]
Sorry, I'm back I have a problem trying on a server version 1.7 / 1.8
http://i.imgur.com/3z2T6l6.jpg
what a pity that you can not solve the chunks :(
Another thing, when I write a letter, I write several "AAAAAA" before the letter that I played
example: "AAAAAAAAAt"
I can thank you very much for everything.

**Comment by khanhduytran0** [comment]
This is a "backscape" system because Minecraft uses different types of inputs. It may be seen when you write a letter But only in some keyboard applications. What keyboard application are you using?

**Comment by JulianARG** [comment]
When it came out the "AAAA" was with the default keyboard of Google or something like that. Then I tried with SwiftKey keyboard and it seems to work fine, I'm not sure why in 1.8 the keyboard does not work with chat, I want to write to login and it does not work, by the way, the option to enter with a premium account is not available, I hope you implement it :)
Can you give me a solution to write in version 1.8? Is that my preferred server is only for that version thanks again.

**Comment by JulianARG** [comment]
No hurry, I just want to let you know the errors that there are, in 1.7.10 the keyboard and chat are perfect, like the multiplayer, the only bad thing is the load of chunks that freezes the game otherwise very good work, congratulations.

**Comment by JulianARG** [comment]
Okay, I discovered this but surely you knew XD, in version 1.9 apparently the loading and saving of chunks does not cause low fps because it is quite playable, obviously the 1.9 is much worse than the 1.7 but does not give those unbearable drops.

**Comment by DanyGames2014** [comment]
@khanhduytran0 do you still develop it or not ?

**Comment by khanhduytran0** [comment]
Probably... because that app have a big probelm. I need a long time to fix...

**Comment by khanhduytran0** [comment]
=>See the link above or click to the link below
https://github.com/zhuowei/Boardwalk/issues/304#issuecomment-427771074

 =>Yes, there a way. Boardwalk had a function available to do it. But now, i don't have time to test any functions.

 =>Current, the mods can't be loaded. That's just a vague idea.

**Comment by DanyGames2014** [comment]
@khanhduytran0
I have that version installed but I just wanted to know if there are newer versions with maybe 1.12.2 version working

**Comment by SiebeDW** [comment]
@khanhduytran0 Are you planning to make your own repo? It actually dont need any files on it but it could be usefull for issue tracker.

**Comment by zhuowei** [comment]
I'm slowing starting to upload Boardwalk's source to GitHub. Please be patient, as I haven't built Boardwalk 1.x in a long time and I need to make sure I have the correct source.

I've uploaded the source of the modified LWJGL and glShim libraries used in Boardwalk to https://github.com/BoardwalkApp.

I'll need to look through the source code of Boardwalk itself before uploading it; that should be up later this week.

Edit: Boardwalk 1.2's source has been pushed as well.

Edit: Boardwalk 2.0's wip source also pushed.

**Comment by leomelki** [comment]
Can someone send me the working apk you've got please?

**Comment by ghost** [comment]
@khanhduytran0 could you link to me your version please?

**Comment by khanhduytran0** [comment]
Here https://youtu.be/kenBd-8u9E8
I takes a lot of times for v2 design and some updates.
EDIT: it may don't  work on your device (android 7 or above)

**Comment by szarik001** [comment]
@khanhduytran0 is there any way to allocate more RAM or is it limited to 512mb?

**Comment by Letfordlay** [comment]
@khanhduytran0 I tried it on my Galaxy s10e running android 9 and when I try to launch any version of the game I get an error
![Screenshot_20190825-204257_PojavLauncher (Java Edition) (1)](https://user-images.githubusercontent.com/21146162/63659826-43902080-c779-11e9-94e1-3478fb354f7a.jpg)
![Screenshot_20190825-204116_PojavLauncher (Java Edition)](https://user-images.githubusercontent.com/21146162/63659827-4428b700-c779-11e9-85ee-e3701d86630a.jpg)
![Screenshot_20190825-203834_PojavLauncher (Java Edition)](https://user-images.githubusercontent.com/21146162/63659828-4428b700-c779-11e9-960d-e40f9258e3d7.jpg)

**Comment by khanhduytran0** [comment]
Now i don't have full time to fix, maybe few days later (by replacing to a new dx)

**Comment by KorewaLidesu** [comment]
@khanhduytran0 did you change the video privacy to private?

**Comment by FunnyBars** [comment]
@khanhduytran0 please give link to your version

**Comment by khanhduytran0** [comment]
It does not work on Android 7.0+ now (i test on emulator) but however you can test it https://drive.google.com/file/d/10jBkQIwBID3Mg6jrdZxkorG2iX4KLr8L/view?usp=drivesdk
Better to test on a real device. It uses dx 1.12 from android sdk 24 (android 7)
On android 7 it will show Unable to Convert. Click ok and play then if see anymore you need repeat .

**Comment by khanhduytran0** [comment]
I forgot "You can't call this activity without profile" because it don't have profile folder. Simple click select user and back then login.

**Comment by FunnyBars** [comment]
thanks!

**Comment by FunnyBars** [comment]
first version runs! But 4 fps)

**Comment by Tiffany-Senpai** [comment]
@khanhduytran0  u got a version that works on android 8 and 9?

**Comment by kran27** [comment]
> It does not work on Android 7.0+ now (i test on emulator) but however you can test it https://drive.google.com/file/d/10jBkQIwBID3Mg6jrdZxkorG2iX4KLr8L/view?usp=drivesdk
> Better to test on a real device. It uses dx 1.12 from android sdk 24 (android 7)
> On android 7 it will show Unable to Convert. Click ok and play then if see anymore you need repeat .

I've tried it on my phone, among other issues once it gets to the actual game, it says

> Error while launching game

Didn't find class "net.minecraft.client.main.Main"
on path: DexPathList[[zip file "/data/data/
net.kdt.pojav launch/app working dir/
libraries/com/mojang/netty/1.6/multidoj/
resources 1572760570119.jar", zip file "/data/data/
net.kdt.pojavlaunch/app_working dir/libraries/
oshi-project/oshi-core/1.1/oshi-core-1.1.jar", zip file
"/data/data/netcat.pojav launch/app working_dir/
libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar",
zip file "/data/data/net.kdt.pojavlaunch/
app_working_dir/libraries/net/java/dev/jna/
platform/3.4.0/platform-3.4.0.jar", zip file "/
java.lang.ClassNotFoundException: Didn't find
class "net.minecraft.client.main.Main" on path:
DexPath List[[dex file "/data/data/net.kdt.pojavlaunch/
app_working dir/version/1.8.9/multidoj/
resources 15728100050901572810008.dex"
dex file "/data/data/net.kat.pojavlaunch/
app working_dir/version/1.8.9/multi doj/
resources 15728331954801572833198.dex",
dex file "/data/data/net.kdt.pojavlaunch/
app_working_dir/version/1.8.9/multidoj/
resources 15728331954801572833201.dex", zip file
"/data/data/net.kdt.pojavlaunch/app_working_dir/
commons-lang3-3.3.2.jar", zip file "/data/data/
net kdt.pojavlaunch/app working dir/libraries/
commons-io/commons-io/2.4/commons-io-2.4.jar", zip
file "/data/data/net.kdt.pojavlaunch/app_working_dir/
libraries/commons-codec/commons-codec/
1.9/commons-codec-1.9.jar", zip file "/data/
data/net.kdt.pojavlaunch/app working dir/
libraries/net/java/jutils/jutils/1.0.0/multidoj/
resources 1572760574840.jar", dex file "/data/data/
inet.kdt.pojavlaunch/app_working_dir/libraries/
com/google/code/gson/gson/2.2.4/multidoj/
resources 15727605815511572760583.dex", zip file
com/paulscode/librarylwjglopenal/20100824/
librarylwjglopenal-20100824.jar", zip file "/data/
data/net.kdt.pojavlaunch/app_working_dir/
libraries/com/paulscode/soundsystem/20120107/
sound system-20120107.jar", zip file "/data/data/
net.kdt.pojavlaunch/app_working_dir/libraries/io/
netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar",
zip file "/data/data/net.kdt.pojavlaunch/
app working_dir/libraries/com/google/guava/
guava/17.0/guava-17.0.jar", zip file "/data/data/
net.kdt.pojav launch/app working_dir/libraries/
org/apache/commons/commons-lang3/3.3.2/
inet.kdt.pojav launch/app working_dir/libraries/net/sf/
jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar", zip
file "/data/data/net.kdt.pojavlaunch/app_working_dir/
libraries/com/paulscode/codecjorbis/20101023/
codecjorbis- 20101023 jar", zip file "/data/
data/net.kdt.pojavlaunch/app_working_dir/
libraries/com/paulscode/codecwav/20101023/
codecwav- 20101023 jar", zip file "/data/data/
net.kdt.pojav launch/app working_dir/libraries/
com/paulscode/libraryjavasound/20101123/
libraryjavasound- 20101123 jar", zip file "/data/data/
net.kdt.pojavlaunch/app working_dir/libraries/
libraries/com/mojang/netty/1.6/multidoj/
resources 1572760570119.jar", zip file "/data/data/
net.kdt.pojav launch/app working_dir/libraries/
oshi-project/oshi-core/1.1/oshi-core-1.1.jar", zip file
"/data/data/net.kdt.pojavlaunch/app_working_dir/
libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar".
zip file "/data/data/net.kdt.pojavlaunch/
app_working_dir/libraries/net/java/dev/jna/
platform/3.4.0/platform-3.4.0.jar", zip file "/
data/data/net.kdt.pojav launch/app working dir/
libraries/com/ibm/icu/icu4j-core-mojang/51.2/
icu4j-core-mojang-51.2.jar", zip file "/data/data/
at

dalvik.system.BaseDexClassLoader.findClass(BaseDex
ClassLoader.java:196)
at java.lang.ClassLoader.loadClass(ClassLoader.java:
379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:
312)

at

net.kdt.pojav launch.MainActivity.runCraft(MainActivity.java:157)
ava:157)

at
net.kdt.pojavlaunch.MainActivity.access$1000042(Unknown
Source:2)

at
net.kdt.pojavlaunch.MainActivity$100000008$100000
007.run(MainActivity.java:521)
at java.util.TimerThread.mainLoop(Timer.java:562)
