### ISSUE TITLE
Cound't find "org_lwjgl_openal_AL.h' when building boardwalk-lwjgl jni by NDK.

### ISSUE THREAD

**Issue by longjunyu2** [zhuowei/Boardwalk#348]
我正在尝试通过Android NDK编译您的LWJGL2.9.1项目，但是遇到了一些问题。
由于我使用的是Windows操作系统，所以我对原项目的Android.mk进行了修改
但是在编译的时候，出现了错误

**Comment by longjunyu2** [comment]
Sorry that I failed to upload picture via Github.Here are some text about the error.

--->
Error while executing process G:\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=G:\Aproject\lwjgl\app\src\main\jni\Android.mk NDK_APPLICATION_MK=G:\Aproject\lwjgl\app\src\main\jni\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=1 APP_PLATFORM=android-19 NDK_OUT=G:/Aproject/lwjgl/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=G:\Aproject\lwjgl\app\build\intermediates\ndkBuild\debug\lib G:/Aproject/lwjgl/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/liblwjgl.so}
[x86_64] Compile        : lwjgl <= android_al.c
G:/Aproject/lwjgl/app/src/main/jni/native/android/android_al.c:36:10: fatal error: 'org_lwjgl_openal_AL.h' file not found
#include "org_lwjgl_openal_AL.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [G:/Aproject/lwjgl/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/lwjgl/native/android/android_al.o] Error 1

	at com.android.build.gradle.tasks.ExternalNativeBuildTaskUtils.executeBuildProcessAndLogError(ExternalNativeBuildTaskUtils.java:245)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.executeProcessBatch(ExternalNativeBuildTask.java:307)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.build(ExternalNativeBuildTask.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 120 more
<---

**Comment by zhuowei** [comment]
@longjunyu2 Did you build lwjgl with ant first? The Java part of LWJGL needs to be built with ant first to generate the native headers.

I haven't touched this in like four years, so sorry if something broke in the meantime.

**Comment by longjunyu2** [comment]
Here is Android.mk to which I had do some modifications.

-->
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_LDLIBS := -llog -lGLESv1_CM
LOCAL_MODULE    := lwjgl

#cfiles := $(shell find -L $(LOCAL_PATH)/native/common -name "*.c" -printf "native/common/%P \n")
#cfiles += $(shell find -L $(LOCAL_PATH)/native/generated/opengl -name "*.c" -printf "native/generated/opengl/%P \n")
#cfiles += $(shell find -L $(LOCAL_PATH)/native/generated/openal -name "*.c" -printf "native/generated/openal/%P \n")
#cfiles += $(shell find -L $(LOCAL_PATH)/native/android -name "*.c" -printf "native/android/%P \n")

LOCAL_SRC_FILES := \
	native/android/android_al.c \
	native/android/extgl_fake.c \
	native/common/common_tools.c \
	native/common/extal.c \
	native/common/org_lwjgl_BufferUtils.c \
	native/common/org_lwjgl_openal_AL.c \
	native/common/org_lwjgl_openal_ALC10.c \
	native/common/org_lwjgl_openal_ALC11.c \
	native/common/opengl/extgl.c \
	native/common/opengl/org_lwjgl_opengl_CallbackUtil.c \
	native/common/opengl/org_lwjgl_opengl_GLContext.c \
	native/linux/opengl/context.c \
	native/linux/opengl/display.c \
	native/linux/opengl/extgl_glx.c \
	native/linux/opengl/GLX.c \
	native/linux/opengl/org_lwjgl_opengl_Display.c \
	native/linux/opengl/org_lwjgl_opengl_LinuxAWTGLCanvasPeerInfo.c \
	native/linux/opengl/org_lwjgl_opengl_LinuxCanvasImplementation.c \
	native/linux/opengl/org_lwjgl_opengl_LinuxContextImplementation.c \
	native/linux/opengl/org_lwjgl_opengl_Pbuffer.c \

LOCAL_C_INCLUDES += $(LOCAL_PATH)/native/common $(LOCAL_PATH)/native/common/opengl $(LOCAL_PATH)/native/android

include $(BUILD_SHARED_LIBRARY) 
<--

**Comment by longjunyu2** [comment]
@zhuowei 谢谢您的回答。在此之前我没有使用ant进行build。我将会再次尝试的，谢谢。:)

**Comment by zhuowei** [comment]
@longjunyu2 Also, I built this on Ubuntu 14.04 - if something breaks, you might want to try building on Linux or Windows Subsystem for Linux.
